### ISSUE TITLE
Last Milestone

### ISSUE THREAD

**Issue by jaspreetKsohal** [jaspreetKsohal/CS594-EDH#24]
Sai:

- [ ] Chart titles, axis and rearrangement components

Jaspreet:

- [ ] Legend of crimes for the map

- [ ] Info panel on map

- [ ] Total number of Vacant-Lots
